### ISSUE TITLE
Strange browsers data

### ISSUE THREAD

**Issue by krpn** [51Degrees/device-detection-data#4]
We are researching jump from v3 Enterprise to v4 Lite and comparing them now. We got strange results related with changing browser:

![image](https://user-images.githubusercontent.com/16793635/143827932-cfb7c235-eb67-41f7-aae9-fd6b2ac3935b.png)

For example, top 10 ua:

![image](https://user-images.githubusercontent.com/16793635/143828296-1bfdcef4-09fb-49ae-99ec-bd953d1661ba.png)

```
Mozilla/5.0 (Linux; Android 11; SM-A515F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; SM-A715F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; M2003J15SC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; SM-A217F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 11; M2102J20SG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 10; MAR-LX1A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Mobile Safari/537.36
```

If I check them in [User Agent tester](http://51degrees.com/developers/user-agent-tester), I will get Chrome Mobile.

Questions:

1. Does v4 Enterprise have the same device list comparing with v4 Lite (according to [v4 Lite README.md](https://github.com/51Degrees/device-detection-data/blob/master/README.md) seems to be true)? Will we get similar browser results using v4 Enterprise?
2. Is v4 Enterprise production ready?
3. Which version of 51Degrees is using in the [User Agent tester](http://51degrees.com/developers/user-agent-tester)?
4. Can you explain this strange results?

**Comment by jwrosewell** [comment]
### List of User-Agents

Regarding the list of User-Agent values you have provided. The following links direct to your User-Agent tester web page and a preliminary check of the results shows that it is correct. The browser is Chrome Mobile. What browser name were you expecting?

[Mozilla/5.0 (Linux; Android 11; SM-A515F) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+SM-A515F)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+Redmi+Note+8+Pro)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+Redmi+Note+9+Pro)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; SM-A715F) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+SM-A715F)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; M2003J15SC) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+M2003J15SC)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 10; Redmi Note 8) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+10%3B+Redmi+Note+8)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 10; Redmi Note 7) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+10%3B+Redmi+Note+7)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; SM-A217F) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+SM-A217F)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 11; M2102J20SG) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+11%3B+M2102J20SG)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)
[Mozilla/5.0 (Linux; Android 10; MAR-LX1A) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/96.0.4664.45 Mobile
Safari/537.36](http://51degrees.com/developers/user-agent-tester?useragent=Mozilla%2F5.0+(Linux%3B+Android+10%3B+MAR-LX1A)+AppleWebKit%2F537.36+(KHTML%2C+like+Gecko)+Chrome%2F96.0.4664.45+Mobile+Safari%2F537.36)

### Q1 - Does v4 Enterprise have the same device list comparing with v4 Lite (according to v4 Lite README.md seems to be true)? Will we get similar browser results using v4 Enterprise?

Lite contains the same profiles. Lite does not contain the same number of properties and is not updated as frequently. Therefore the lite data file will not know about the latest versions or devices.

### Q2 - Is v4 Enterprise production ready?

Yes. It was released in June 2020. All the APIs include automated tests and CI/CD scripts. You can see a full change history in GitHub commits and we track issues also via GitHub.

### Q3 - Which version of 51Degrees is using in the User Agent tester?

Version 4.3 with the latest Enterprise data files.

### Q4 - Can you explain this strange results?

I assume you are referring to the image at the top of the original issue. If so then it is hard to be certain without seeing the data. If the two data files being used were taken at a very different point in time then that would be a factor. Also any corruption of the input values such as quote characters or other alterations to character positions would impact V4 more than V3. Can you provide the input data used in your test?

**Comment by ElDuchino** [comment]
@jwrosewell we've just tested a new lite version and result is correct(chrome mobile matches to chrome mobile, not to chrome). I assume we can close issue.

**Comment by krpn** [comment]
@jwrosewell, thank you for answer. Closing...
